name: CI Pipeline

on:                             # <-- required
  push:                         # Trigger when code is pushed
    branches:
      - main
  pull_request:                 # Trigger on PRs
    branches:
      - main

jobs:                           # <-- required
  test:
    runs-on: ubuntu-latest      # Which machine to use
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest streamlit

      - name: Run tests
        run: |
           pytest -v
